#!/bin/bash
#
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=4
#SBATCH --time=6:00:00
#SBATCH --mem=10GB
#SBATCH --job-name=acwg-clamp-b
#SBATCH --mail-type=END
#SBATCH --mail-user=ls4411@nyu.edu
#SBATCH --output=dcgan_\%j.out

module purge
module load python/intel/2.7.12
module load cuda/8.0.44
module load cudnn/8.0v5.1
module load scikit-learn/intel/0.18.1

pip install http://download.pytorch.org/whl/cu80/torch-0.1.11.post5-cp27-none-linux_x86_64.whl --user
pip install torchvision --user

python neuralnet.py --cuda
